### ISSUE TITLE
Fix internal arm vs arm64 labels

### ISSUE THREAD

**Issue by klutchell** [product-os/self-hosted-runners#10]
We are generating labels in here that appear as arm64/aarch64 even on the armv7 runners.
https://github.com/product-os/self-hosted-runners/blob/99dd48583cdfb7c94c641db7b155bf90fc301c1c/runner/balena.sh#L75-L76

**Comment by ab77** [comment]
One could argue that this is technically correct, because the "machine" this is running on is `aarch64/arm64`, but the software is told to lie and report a lower architecture. In either case, `dpkq` doesn't use the same system call, so it always reports the underlying hardware arch:

```
$ setarch linux32 dpkg --print-architecture
arm64
```

**Comment by klutchell** [comment]
Here is the root cause: https://github.com/balena-io/remote-builders/issues/18

Some labels are reporting userspace architecture, which is currently from the wrong image for armv7. Fix that in order to fix this.
