### ISSUE TITLE
iptables are disabled preventing use of custom networks

### ISSUE THREAD

**Issue by klutchell** [product-os/self-hosted-runners#21]
iptables was initially disabled in the runner so it could pass dind tests when emulated (QEMU does not play well with iptables).

If a docker-compose test wants to use a custom network, it will not have internet access since we disabled iptables on the docker engine.

Rather than re-enable iptables let's use it as a forcing function to ensure tests aren't accessing the internet when they should be using mocks, etc.

**Comment by klutchell** [comment]
Enabling iptables would also require [re-ordering these two steps](https://github.com/product-os/self-hosted-runners/blob/5b2f56e438839d92cc635e4e50025730dd3a30c6/runner/docker-compose.test.yml#L46-L59).

**Comment by ab77** [comment]
with `--iptables=false` there is no networking full stop (to the outside at least).

**Comment by klutchell** [comment]
Resolved by https://github.com/product-os/self-hosted-runners/pull/30
